// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ouY_IIjbAeDZX9lMPPsOTi3zwnvGsoM',
    appId: '1:479470550743:web:89724bc137895fe7c97a92',
    messagingSenderId: '479470550743',
    projectId: 'my-festival-55mr',
    authDomain: 'my-festival-55mr.firebaseapp.com',
    storageBucket: 'my-festival-55mr.firebasestorage.app',
    measurementId: 'G-9PE00DPX62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhO3jQftiBrVVUEfQBVzGiuvdEMwraXP4',
    appId: '1:479470550743:android:62a7ad43524b06f1c97a92',
    messagingSenderId: '479470550743',
    projectId: 'my-festival-55mr',
    storageBucket: 'my-festival-55mr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk91-lj8OcnqFTK5sQJUx2PvrGBAnZAE8',
    appId: '1:479470550743:ios:b9843a5f411055ecc97a92',
    messagingSenderId: '479470550743',
    projectId: 'my-festival-55mr',
    storageBucket: 'my-festival-55mr.firebasestorage.app',
    iosBundleId: 'com.example.fcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk91-lj8OcnqFTK5sQJUx2PvrGBAnZAE8',
    appId: '1:479470550743:ios:b9843a5f411055ecc97a92',
    messagingSenderId: '479470550743',
    projectId: 'my-festival-55mr',
    storageBucket: 'my-festival-55mr.firebasestorage.app',
    iosBundleId: 'com.example.fcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ouY_IIjbAeDZX9lMPPsOTi3zwnvGsoM',
    appId: '1:479470550743:web:be9687e333679b56c97a92',
    messagingSenderId: '479470550743',
    projectId: 'my-festival-55mr',
    authDomain: 'my-festival-55mr.firebaseapp.com',
    storageBucket: 'my-festival-55mr.firebasestorage.app',
    measurementId: 'G-W2EWJLF39H',
  );
}
